global:
  scrape_interval: 5s   # cada cuánto recoge métricas

scrape_configs:
  - job_name: "unigo"
    static_configs:
      - targets: ["host.docker.internal:8000"]
        # si usas Linux nativo / WSL: ["localhost:8000"]
